class FuseError(Exception): ...
class error(Exception): ...

def FuseAPIVersion(*args, **kwargs) -> int: ...
def FuseGetContext(*args, **kwargs) -> dict[str, int]: ...
def FuseInvalidate(*args, **kwargs) -> int: ...
def FuseNotifyPoll(*args, **kwargs) -> int: ...
def main(*args, **kwargs) -> None: ...
